### ISSUE TITLE
ModuleNotFoundError: No module named 'slugify'

### ISSUE THREAD

**Issue by ywu** [Opus10/footing#7]
Hi I got the following error when running `footing update`:

```
> footing update -v 1.7.12 
Creating branch _footing_update for processing the update
Creating temporary working branch _footing_update_temp
Traceback (most recent call last):
  File "/home/wu/.local/lib/python3.10/site-packages/cookiecutter/environment.py", line 37, in __init__
    super(ExtensionLoaderMixin, self).__init__(extensions=extensions, **kwargs)
  File "/home/wu/.local/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/home/wu/.local/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/home/wu/.local/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/home/wu/.local/lib/python3.10/site-packages/cookiecutter/extensions.py", line 15, in <module>
    from slugify import slugify as pyslugify
ModuleNotFoundError: No module named 'slugify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wu/.local/bin/footing", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/wu/.local/lib/python3.10/site-packages/footing/cli.py", line 89, in update
    footing.update.update(new_version=version, enter_parameters=enter_parameters)
  File "/home/wu/.local/lib/python3.10/site-packages/footing/utils.py", line 95, in wrapper
    ret_val = function(*args, **kwargs)
  File "/home/wu/.local/lib/python3.10/site-packages/footing/update.py", line 199, in update
    _apply_template(old_template, ".", checkout=old_version, extra_context=footing_config)
  File "/home/wu/.local/lib/python3.10/site-packages/footing/update.py", line 54, in _apply_template
    repo_dir = cc_main.cookiecutter(
  File "/home/wu/.local/lib/python3.10/site-packages/cookiecutter/main.py", line 93, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/home/wu/.local/lib/python3.10/site-packages/cookiecutter/prompt.py", line 183, in prompt_for_config
    env = StrictEnvironment(context=context)
  File "/home/wu/.local/lib/python3.10/site-packages/cookiecutter/environment.py", line 67, in __init__
    super(StrictEnvironment, self).__init__(undefined=StrictUndefined, **kwargs)
  File "/home/wu/.local/lib/python3.10/site-packages/cookiecutter/environment.py", line 39, in __init__
    raise UnknownExtension('Unable to load extension: {}'.format(err))
cookiecutter.exceptions.UnknownExtension: Unable to load extension: No module named 'slugify'
```

**Comment by ywu** [comment]
`footing` installation was messed up somehow.
